name: reciprocity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^5.0.5955
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.0
  fluttertoast: ^8.2.6
  shared_preferences: ^2.2.3
  jitsi_meet_flutter_sdk: ^0.4.2

dev_dependencies:
  change_app_package_name: ^1.2.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/
